apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: configstore
  namespace: evolution
spec:
  type: configuration.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis-master.default.svc.cluster.local:6379
  - name: redisPassword
    value: password@1