apiVersion: apps/v1
kind: Deployment
metadata:
  name: uploader-api-deployment
  namespace: evolution


spec:
  replicas: 1
  selector:
    matchLabels:
      app: uploader-api
  template:
    metadata:
      labels:
        app: uploader-api
    spec:
      containers:
      - name: uploader-api
        image: rohitrustagi007/evo_uploader:latest
        imagePullPolicy: Always
        env: 
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
          - name: AWS_ACCESS_KEY
            valueFrom: 
              secretKeyRef:
                name: access 
                key: AWS_ACCESS_KEY
          - name: AWS_SECRET_KEY
            valueFrom: 
              secretKeyRef:
                name: secret 
                key: AWS_SECRET_KEY       
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

