apiVersion: v1
kind: Service
metadata:
  name: uploader-api-cluster-ip
  namespace: evolution
spec:
  type: ClusterIP
  selector:
    app: uploader-api
  ports:
  - name: uploader-api-port
    protocol: TCP
    port: 80
    targetPort: 80